---
date: "`r Sys.Date()`" 
output:
  html_document:
    theme: default
    highlight: espresso
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, results = TRUE, message = FALSE, warning = FALSE)
```


```{r results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library (readr)
library(RMySQL)
```


### Load data from RDS into R
### Initialize RDS Database connection
```{r}
user <-'admin'
password <-'!passKey607'
host<-'data607-project2.cbs1lxtno2zh.us-east-2.rds.amazonaws.com'

dbname <-'d_607_p3'
connection = dbConnect(MySQL(), user = user, password = password, dbname = dbname, host = host)
```

### Get data function
```{r}
get_data<- function(table_name) {
dataset <- tbl(connection,dbplyr::in_schema(dbname, table_name))
  return(dataset)
}
```

### The following is the query that returns all relevant records for project 3
```{r}


d607_p3_all_recs<-as.data.frame(get_data('view_d607_p3_all_recs'))

tibble(d607_p3_all_recs)

head(d607_p3_all_recs)

```
#The following are the list of tables used


```{r tblcompany}

tblcompany<-as.data.frame(get_data('company'))

tibble(tblcompany)

```


```{r tblcemployee}

tblcemployee<-as.data.frame(get_data('company_employee'))

tibble(tblcemployee)

```


```{r tblcindustry}

tblcindustry<-as.data.frame(get_data('company_industry'))

tibble(tblcindustry)

```


```{r tblcrevenue}

tblcrevenue<-as.data.frame(get_data('company_revenue'))

tibble(tblcrevenue)

```


```{r tbljobmaster}

tbljobmaster<-as.data.frame(get_data('job_master'))

tibble(tbljobmaster)

```


```{r tbljobskills}

tbljobskills<-as.data.frame(get_data('job_skills'))

tibble(tbljobskills)

```


```{r tblsalary}

tblsalary<-as.data.frame(get_data('salary'))

tibble(tblsalary)

```


```{r tblskills}

tblskills<-as.data.frame(get_data('skills'))

tibble(tblskills)

```


```{r tblstate}

tblstate<-as.data.frame(get_data('state'))

tibble(tblstate)

```
